### ISSUE TITLE
Use latest SSE2NEON

### ISSUE THREAD

**Issue by jserv** [scopedog/gf-nishida-16#3]
commit [add344fe](https://github.com/scopedog/gf-nishida-16/commit/add344fe2fd664ee983182e4011d4c80d0a26d0d) included SSE2NEON for Arm porting. However, the header file was considered as outdated, and you might instead take the latest [SSE2NEON](https://github.com/DLTcollab/sse2neon), which introduces bug fixes and more SSE intrinsics.

**Comment by scopedog** [comment]
OK. Thanks.
I'll replace it with a new one.

**Comment by animetosho** [comment]
Would recommend considering just using ARM intrinsics - it shouldn't be too hard, and if it helps, [here's a reference](https://github.com/animetosho/ParPar/blob/469dfa8bf6cd48e8949c82eab83b30f478adcc20/gf16/gf16_shuffle_neon.c#L161-L176) with most of what you'll likely need.  
It let's you take advantage of ARM-specific stuff like interleaved loads/stores ((`vld2q_u8`/`vst2q_u8`)[https://github.com/animetosho/ParPar/blob/469dfa8bf6cd48e8949c82eab83b30f478adcc20/gf16/gf16_shuffle_neon.c#L292-L294]), which saves you from the pack/unpack routine.

**Comment by scopedog** [comment]
I have replaced the regular loads and stores with the interleaved ones. Yes, they are so fast and it was really fun to see the benchmark results. Thank you.
Now it's time to redo the benchmark. I'll be able to finish it by the end of next week if nothing happens.
